image: ruby:2.3

build:
  stage: build
  script:
  - apt-get update
  - apt-get install -y node
  - apt-get install -y npm
  - npm install
  - npm install -g grunt-cli
  - npm install -g grunt
  - npm install -g bower
  - gem install jekyll
  - bower install --allow-root
  - grunt
