image: ubuntu:latest

build:
  stage: build
  script:
  - apt-get update
  - apt-get install -y nodejs
  - apt-get install -y npm
  - apt-get install -y ruby
  - npm install
  - npm install -g grunt-cli
  - npm install -g grunt
  - npm install -g bower
  - gem install jekyll
  - bower install --allow-root
  - grunt
