# Site settings
title: Bed and Breakfast am Bühlberg
email: info@ml-software.ch
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:1337" # the base hostname & protocol for your site

OnSeason: ab 27. Dezember 2015 bis 10. April 2016 und ab 06. Juni 2016 bis 16. Oktober 2016
OffSeason: ab 11. April 2016 bis 05. Juni 2016 und ab 17. Oktober 2016 bis 18. Dezember 2016
PriceDog: 15
ExtraPriceSingleInDouble: 30
DinnerReservationUntil: 11
DinnerPrice: 30

collections:
  rooms:
      output: false

# Build settings
markdown: kramdown

exclude: [bower.json, package.json, gruntfile.js]